In [1]:
import numpy as np
np.set_printoptions(threshold=10000,suppress=True)
import pandas as pd
import warnings
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')

data = pd.read_csv('./villes.csv', sep=';')


#print(data);
#data.head();

X = data.iloc[:, 1:].values
labels = data.iloc[:, 0].values
print(labels)


from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

SC = StandardScaler()
SC.fit(X)
Xnorm = SC.transform(X)
print(X, Xnorm)
"""
y1  = a1*janv + b1*fev + .... + l1 * dec
y2  = a2*janv + b2/fev + ....
...
y12 = a12*janv + b12*dev+ ....

importance(y1) = alpha1/sum(alapha)
"""

pca=PCA(n_components = 12)
print(Xnorm, pca)
pca.fit(Xnorm)

print("explained_variance_", pca.explained_variance_)

print("explained_variance_ratio_", pca.explained_variance_ratio_)


['ajac' 'ange' 'ango' 'besa' 'biar' 'bord' 'bres' 'cler' 'dijo' 'embr'
 'gren' 'lill' 'limo' 'lyon' 'mars' 'mont' 'nanc' 'nant' 'nice' 'nime'
 'orle' 'pari' 'perp' 'reim' 'renn' 'roue' 'stqu' 'stra' 'toul' 'tlse'
 'tour' 'vich']
[[ 7.7  8.7 10.5 12.6 15.9 19.8 22.  22.2 20.3 16.3 11.8  8.7]
 [ 4.2  4.9  7.9 10.4 13.6 17.  18.7 18.4 16.1 11.7  7.6  4.9]
 [ 4.6  5.4  8.9 11.3 14.5 17.2 19.5 19.4 16.9 12.5  8.1  5.3]
 [ 1.1  2.2  6.4  9.7 13.6 16.9 18.7 18.3 15.5 10.4  5.7  2. ]
 [ 7.6  8.  10.8 12.  14.7 17.8 19.7 19.9 18.5 14.8 10.9  8.2]
 [ 5.6  6.6 10.3 12.8 15.8 19.3 20.9 21.  18.6 13.8  9.1  6.2]
 [ 6.1  5.8  7.8  9.2 11.6 14.4 15.6 16.  14.7 12.   9.   7. ]
 [ 2.6  3.7  7.5 10.3 13.8 17.3 19.4 19.1 16.2 11.2  6.6  3.6]
 [ 1.3  2.6  6.9 10.4 14.3 17.7 19.6 19.  15.9 10.5  5.7  2.1]
 [ 0.5  1.6  5.7  9.  13.  16.4 18.9 18.3 15.3 10.1  4.6  0.5]
 [ 1.5  3.2  7.7 10.6 14.5 17.8 20.1 19.5 16.7 11.4  6.5  2.3]
 [ 2.4  2.9  6.   8.9 12.4 15.3 17.1 17.1 14.7 10.4  6.1  3.5]
 [ 3.1  3.9  7.